### PR TITLE
added .env file for dctoken and containerfile

### PR DESCRIPTION
**Pull request by led0nk**
added .env file + containerfile

### CODE REVIEW

**Comment by LecrisUT** [comment]
So the first error you have there is that packit replaces the last `echo` command you have in `actions.create-archive` at the `%setup` macro. So a quick fix would be to add
```yaml
- sh -c "name-of-archive-maybe-with-wildcard-*.tar.gz"
```

**Comment by led0nk** [comment]
> So the first error you have there is that packit replaces the last `echo` command you have in `actions.create-archive` at the `%setup` macro. So a quick fix would be to add
> 
> ```yaml
> - sh -c "name-of-archive-maybe-with-wildcard-*.tar.gz"
> ```

I'm totally sorry, but i have to admit that i don't know where in code we are looking at?
When i put it in context, i guess you are pointing at the end of `make archive ` where i print out the tarball-name including the path.

I'm even more confused because the logs are looking like the creation of the srpm worked well and that should clearly be after making and handing over the tarball?

**Comment by LecrisUT** [comment]
> I'm totally sorry, but i have to admit that i don't know where in code we are looking at?

https://github.com/led0nk/ark-clusterinfo/blob/e6d3f167a9d38ef7f7ca3bb93f76e7e08ee9a5e6/.packit.yaml#L23-L26

> I'm even more confused because the logs are looking like the creation of the srpm worked well and that should clearly be after making and handing over the tarball?

Indeed the archive was created, but packit doesn't know what is the filename of the main archive that you've created (the one that it needa to use in `%setup -n`). That's why you need an additional echo command there.

Roughly the process that packit does is: `create-archive` -> `fix-specfile` (change `Source`, `%setup` and `Version`/`Release`) -> `create-srpm` -> build rpms

**Comment by led0nk** [comment]
> https://github.com/led0nk/ark-clusterinfo/blob/e6d3f167a9d38ef7f7ca3bb93f76e7e08ee9a5e6/.packit.yaml#L23-L26
> 


So i added in `sh -c "echo ark-clusterinfo-0.1.0.tar.gz"` which indeed seems to work, even locally. But it doesn't seem to affect the problem where packit somehow references the archive or the buildfolder as `.`

**Comment by LecrisUT** [comment]
```
2024-05-25 20:34:28.822 upstream.py       DEBUG  Trying to extract archive_root_dir from known archives
2024-05-25 20:34:28.823 upstream.py       DEBUG  Archive ark-clusterinfo-0.1.0.tar.gz is tar.
2024-05-25 20:34:28.860 upstream.py       DEBUG  Directory . found in archive ark-clusterinfo-0.1.0.tar.gz
```

This part is suspicious. When you make the tar, I guess you didn't put it in a sub-folder, e.g. using `--prefix`

**Comment by led0nk** [comment]
https://github.com/led0nk/ark-clusterinfo/blob/e6d3f167a9d38ef7f7ca3bb93f76e7e08ee9a5e6/Makefile#L77-L93

Well actually i somehow do..
I copy the needed directories into the `_build/parentdir` and at the end i just archive everything inside `_build`, which should be the `parentdir`.

**Comment by LecrisUT** [comment]
> Well actually i somehow do.. I copy the needed directories into the `_build/parentdir` and at the end i just archive everything inside `_build`, which should be the `parentdir`.

But probably you were archiving as a flat structure, while packit seems to assume everything is under a subfolder in the archive. That is partly on purpose because when it comes to publishing downstream 99% it's in that structure, e.g. git archive from github.

> Now I'm facing some problems with the directorypaths, because it seems like i don't put the correct directory for building.

A tip: most commands may become more intuitive if you use the default git archive directly, i.e. use the same build commands you would do right after a git clone.

Go is a bit tricky because it typically downloads the missing dependencies which is against packaging guidelines. For debugging purposes, maybe you can still do that in copr by enabling network, but eventually it should follow the [Fedora packaging guidelines for golang](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/) (even when packaging outside of Fedora) which uses the dependencies defined in Fedora instead of those downloaded.

**Comment by led0nk** [comment]
> Go is a bit tricky because it typically downloads the missing dependencies which is against packaging guidelines. For debugging purposes, maybe you can still do that in copr by enabling network, but eventually it should follow the [Fedora packaging guidelines for golang](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/) (even when packaging outside of Fedora) which uses the dependencies defined in Fedora instead of those downloaded.

Actually i'm trying to avoid this dependency/network problem by providing the vendor files, so that shouldn't be a problem at all. Or at least this should be a "workaround".

So for now i'm just trying to figure out how to put in the correct buildpath into `%build`, which should be the unpacked tarball i guess.

**Comment by LecrisUT** [comment]
You can consider the spec file as a plain bash script, so feel free to use `pwd`, `cd`, `tree`, etc. You can also dothe following to have an interactive shell 
```console
$ packit build in-mock
$ mock --shell
```

> Actually i'm trying to avoid this dependency/network problem by providing the vendor files, so that shouldn't be a problem at all. Or at least this should be a "workaround".

For upstream and providing inside a copr environment or such, that's fine. Just keep in mind that for downstream it's against guidelines.

It is a major pain to have to manage a full chain of dependencies for packaging, but that's how things have to be done for system packages (for many reasons: licensing, monitoring, conflicting installation paths, shared library, etc.). Sometimes flatpak is more beneficial for such reasons.

But of course if you go with the system packaging, the GO-SIG will help with managing, reviewing and packaging the dependencies.

**Pull request merged**
